# Generated by Django 5.0 on 2024-05-10 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_rack', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaserackdrinkrack',
            old_name='capacity',
            new_name='drink_quantity',
        ),
    ]
